services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"

  client:
    build: ./client
    volumes:
      - ./cient:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - server

  migrate:
    build: ./server
    # The 'migrate' service will run the migrations.
    # It must have the same environment variables as the 'app' service to connect to the DB.
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    # We don't need to expose ports for this service
    # We will run commands manually
    command: "true" # A no-op command to keep the container from exiting immediately
volumes:
  db-data:
