version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: chirp_dev
      POSTGRES_PASSWORD: ChirpSecretPassword88+
      POSTGRES_DB: chirp_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
